name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip

      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: clone libnfs
        run: |
          git clone https://github.com/sahlberg/libnfs
          
      - name: install libnfs into PS2SDK
        run: |
            cd libnfs/ps2_ee
            make -f Makefile.PS2_EE install
            
      - name: Compile wLaunchELF
        run: |
          make
          git ls-files -i --exclude-standard -c

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
          path: BOOT.ELF

      - name: Create release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: BOOT.ELF
